### ISSUE TITLE
Inconsistency in JSON-LD example of the PublicTransportStop data model?

### ISSUE THREAD

**Issue by flopezag** [smart-data-models/dataModel.UrbanMobility#23]
I was checking the content of the [example.jsonld](https://github.com/smart-data-models/dataModel.UrbanMobility/blob/master/PublicTransportStop/examples/example.jsonld) and I am not sure if the "type" properties are correct in this case. Should not be "Property" and "Relationships"?

BTW, Is it "StructuredValue" a valid "type" in JSON-LD?

**Comment by albertoabellagarcia** [comment]
You were right. Fixed
